name: csumb-user-image
# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  - git  #==2.51.0
  - ipython  #==9.7.0
  - jupyter-resource-usage=1.2.0
  - jupyterhub==5.3.0
  - jupyterlab==4.5
  - jupyter-archive==3.4.0
  - jupyter_server==2.16.0
  - jupyterlab-git==0.51.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.16.6
  - nbgitpuller==1.2.2
  - notebook==7.5.0
  - python==3.11.*
  - pip==25.1.1

  # vscode
  - code-server==4.106.2
  - jupyter-vscode-proxy==0.7
  - jupyter-server-proxy==4.4.0

  - sage==10.7

  # data science
  - datascience==0.18.1
  - matplotlib==3.10.3
  - numpy==2.3.0
  - geopandas==1.1.0
  - openpyxl==3.1.5
  - pandas==2.3.0
  - plotly==6.1.2
  - scikit-learn==1.7.0
  - scipy==1.15.2
  - seaborn==0.13.2
  - statsmodels==0.14.4
  - sympy==1.14.0

  # pip installed packages, conda is preferred
  - pip:
    - jupyterlab-a11y-checker==0.2.5
    # useful for debugging python package issues
    - pip-tree==4.0.0
    - pipdeptree==2.28.0

    - nbconvert[webpdf]==7.16.6
    - otter-grader==6.1.3
